name: 'Git Mirror with New Commit'
description: 'mirror source repo to destination repo with a new commit via ssh.'
branding:
  icon: 'copy'
  color: 'orange'
inputs:
  source_repo:
    description: 'Source repo.'
    required: true
  source_branch:
    description: 'Source branch.'
    required: false
  source_key:
    description: 'SSH private key for source repo.'
    required: false
  destination_repo:
    description: 'Destination repo.'
    required: true
  destination_branch:
    description: 'Destination branch.'
    required: false
  destination_key:
    description: 'SSH private key for destination repo.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
