name: Git Mirror with New Commit
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: mirror
        uses: sunn4room/git-mirror-with-new-commit@main
        with:
          source_repo: https://github.com/sunn4room/test-git-mirror.git
          destination_repo: git@gitee.com:sunn4room/test-git-mirror.git
          destination_key: ${{ secrets.SSH_PRIVATE_KEY }}
